server:
  port: 8761
  
spring:
  application:
    name: Eureka-Service
  datasource:
    tomcat: 
      initial-size: 1
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
