server:
  port: 50005

spring:
  application:
    name: user-service
  datasource:
    tomcat: 
      initial-size: 1
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: p3user
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
  mvc:
    dispatchOptionsRequest: true 

keystore:
  password: mySecretKey
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://18.221.160.13:8761/eureka
